[package]
name = "completion-generator"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
archive = { path = "../archive" }
fourier-series = { path = "../fourier-series" }
clap = "4.0.26"
clap_complete = "4.0.5"
once_cell = "1.16.0"
