[package]
name = "anybase"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.1.13", features = ["derive"] }
num = { version = "0.4.0", features = ["num-bigint"] }
anyhow = "1.0.70"
