[package]
name = "git-commit-time-stat"
version = "1.0.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bczhc_lib = { path = "../../lib", version = "1.0.0" }
clap = "2.33.3"
chrono = "0.4.19"
git2 = "0.13.21"
