[package]
name = "fourier-series"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.0.22"
num_cpus = "1.14.0"
once_cell = "1.16.0"
bczhc_lib = { path = "../../lib" }
