[package]
default-run = "main"
name = "rust"
version = "1.0.0"
authors = ["bczhc <bczhc0@126.com>"]

[[bin]]
name = "main"
path = "src/demo.rs"

[[bin]]
name = "utf-converter"
path = "src/utf_converter.rs"

[[bin]]
name = "character-statistics"
path = "src/character_statistics.rs"

[dependencies]
#rand = "0.8.3"
#rusqlite = "0.25.1"
#libc = "0.2.93"
lib = {path = "lib", version = "1.0.0"}
#num-complex = "0.4.0"