[package]
default-run = "main"
name = "main"
version = "1.0.0"
authors = ["bczhc <bczhc0@126.com>"]

[[bin]]
name = "utf-converter"
path = "src/app/utf-converter.rs"

[[bin]]
name = "main"
path = "src/main.rs"