[package]
default-run = "demo"
name = "rust"
version = "1.0.0"
authors = ["bczhc <bczhc0@126.com>"]
license = "MIT"
edition = "2018"

[workspace]
members = [
    "apps/character_statistics",
    "apps/file_size",
    "apps/reverse",
    "apps/shuffle_string",
    "apps/stdin_size",
    "apps/utf-converter",
]

[[bin]]
path = "src/demo.rs"
name = "demo"

[dependencies]
lib = { path = "lib", version = "1.0.0" }