[package]
default-run = "demo"
name = "rust"
version = "1.0.0"
authors = ["bczhc <bczhc0@126.com>"]
license = "MIT"
edition = "2018"

[workspace]
members = [
    "apps/character_statistics",
    "apps/file_size",
    "apps/reverse",
    "apps/shuffle_string",
    "apps/stdin_size",
    "apps/utf-converter",
    "apps/file_and_bitmap_streamed_converter",
    "apps/cpu_loop",
    "apps/char_count",
    "apps/regex-test",
    "apps/transfer",
    "apps/base256",
    "apps/wrap",
    "tool",
]

[[bin]]
path = "src/demo.rs"
name = "demo"

[[bin]]
path = "src/fourier_series_demo.rs"
name = "fourier-series-demo"

[[bin]]
path = "src/demo1.rs"
name = "demo1"

[dependencies]
bczhc_lib = { path = "./lib", version = "1.0.0" }
libc = "0.2.95"
errno = "0.2.7"
clap = "2.33.3"
num_cpus = "1.13.0"
encoding_rs = "0.8.28"
regex = "1.5.4"
rand = "0.8.4"
terminal_size = "0.1.17"
hound = "3.4.0"
byteorder = "1.4.3"
threadpool = "1.8.1"
num = "0.4.0"
