[package]
default-run = "demo"
name = "rust"
version = "1.0.0"
authors = ["bczhc <bczhc0@126.com>"]
license = "MIT"
edition = "2018"

[workspace]
members = [
    "apps/character_statistics",
    "apps/file_size",
    "apps/reverse",
    "apps/shuffle_string",
    "apps/stdin_size",
    "apps/utf-converter",
    "apps/file_and_bitmap_streamed_converter",
    "apps/cpu_loop",
    "apps/char_count",
    "apps/regex",
    "apps/transfer",
    "apps/base256",
    "apps/wrap",
    "apps/git_commit_time_statistics",
]

[[bin]]
path = "src/demo.rs"
name = "demo"

[[bin]]
path = "src/fourier_series_demo.rs"
name = "fourier-series-demo"

[dependencies]
bczhc_lib = { path = "./lib", version = "1.0.0" }
libc = "0.2.95"
errno = "0.2.7"
clap = "2.33.3"
num_cpus = "1.13.0"
regex = "1.5.4"
rusqlite = "0.26.3"
rand = "0.8.4"
