[package]
name = "cpu-loop"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "concurrent-test"
path = "src/concurrent.rs"

[dependencies]
num_cpus = "1.13.0"
