[package]
name = "utf-converter"
version = "1.0.0"
authors = ["bczhc <bczhc0@126.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lib = {path = "../../lib", version = "1.0.0"}
clap = "2.33.3"