[package]
name = "binary-input"
version = "1.0.0"
edition = "2021"

[dependencies]
quick-error = "2.0.1"
bczhc_lib = {path = "../../lib"}

[target.'cfg(unix)'.dependencies]
libc = "0.2.140"
termios = "0.3.3"
console = "0.15.5"
