[package]
name = "x11-event-monitor"
version = "1.0.0"
edition = "2021"

[dependencies]
winit = "0.28.3"
libc = "0.2.132"
chrono = "0.4.22"
bczhc_lib = { path = "../../lib" }
x11-clipboard = "0.7.1"
proc-macro2 = "1.0.52"
serde = { version = "1.0.157", features = ["derive"] }
serde_json = "1.0.52"
clap = "4.1.11"

[target.'cfg(unix)'.dependencies]
libxdo-sys = "0.11.0"