[package]
name = "char-count"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bczhc_lib = { path = "../../lib", version = "1.0.0" }
clap = "4.0.26"
unicode-segmentation = "1.10.0"