[package]
name = "forward"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bczhc_lib = { path = "../../lib", version = "1.0.0" }
clap = "3.1.8"
once_cell = "1.10.0"
thiserror = "1.0.30"