[package]
name = "send-email"
version = "1.0.0"
edition = "2021"

[dependencies]
clap = "4.1.13"
lettre = { version = "0.10.4", default-features = false, features = [
    "smtp-transport",
    "pool",
    "hostname",
    "builder",
    "rustls-tls"
] }
toml = "0.7.6"
anyhow = "1.0.72"
