[package]
name = "btc-tools"
version = "0.1.0"
edition = "2021"

[dependencies]
bitcoin = { version = "0.30.1", features = ["rand"] }
rand = "0.8.5"
clap = { version = "4.4.6", features = ["derive"] }
anyhow = "1.0.75"
num_cpus = "1.16.0"
hex = "0.4.3"
