[package]
name = "wav-wrapper"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.9", features = ["derive"] }
hound = "3.5.1"
byteorder = "1.5.0"
anyhow = "1.0.86"
stream-num-reader = { path = "../../libs/stream-num-reader" }