# This is a basic workflow to help you get started with Actions

name: rust CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Clone rust-lib-doc
        uses: actions/checkout@master
        with:
          repository: bczhc/rust-lib-doc
          token: ${{ secrets.GITHUB_TOKEN }}
          path: ./rust-lib-doc

#      - name: Install Rust
#        run: sudo apt install rustc -y
#      - name: build
#        run: cargo build -j4
#      - name: Test lib
#        run: cargo test -p lib
      - name: Deploy documentation and push to rust-lib-doc repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd rust-lib-doc
          touch test
          git add test
          git commit -m test
          git push origin gh-pages
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: documentation
          path: documentation.tgz
