[package]
name = "archive"
version = "1.0.0"
edition = "2021"

[dependencies]
clap = "4.0.10"
byteorder = "1.4.3"
flate2 = "1.0.24"
xz2 = "0.1.7"
zstd = "0.11.2+zstd.1.5.2"
walkdir = "2.3.2"
pathdiff = "0.2.1"
crc = "3.0.0"
thiserror = "1.0.35"
bczhc_lib = { path = "../../lib" }
once_cell = "1.14.0"
cfg-if = "1.0.0"
num-traits = "0.2.15"
num-derive = "0.3.3"